// Code generated by hero.
// source: C:\work\Go\src\SiteGo\template\contact.html
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/labstack/echo"
	"github.com/shiyanhui/hero"
)

func Contact(c echo.Context, buffer *bytes.Buffer) {
	buffer.WriteString(`
<h3>Contact</h3>
`)
	if c.FormValue("name") != "" {
		buffer.WriteString(`
<div class="alert alert-success" role="alert">
Message sent for `)
		hero.EscapeHTML(c.FormValue("name"), buffer)
		buffer.WriteString(` from `)
		hero.EscapeHTML(c.FormValue("email"), buffer)
		buffer.WriteString(`.
</div>
`)
	} else {
		buffer.WriteString(`
<form method="POST">
<p>(No email is sent, the name and email will be just displayed on submission.)</p>
<div class="form-group row">
    <label for="name" class="col-sm-2 col-form-label">Name</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" id="name" name="name">
    </div>
</div>
<div class="form-group row">
    <label for="email" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
        <input type="email" class="form-control" id="email" name="email">
    </div>
</div>
<div class="form-group">
        <label for="msg">Message</label>
        <textarea class="form-control" id="msg" name="msg" rows="7"></textarea>
      </div>
<div class="d-flex justify-content-center">
    <button class="btn waves-effect waves-light btn-success" type="submit">Send</button>
</div>
</form>
`)
	}

}
