// Code generated by hero.
// source: C:\work\Go\src\SiteGo\template\error.html
// DO NOT EDIT!
package template

import "bytes"

func Error(buffer *bytes.Buffer) {
	buffer.WriteString(`
<h3>Error 404</h3>
<p>Page not found</p>`)

}
