// Code generated by hero.
// source: C:\work\Go\src\SiteGo\template\home.html
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"
)

func Home(site string, buffer *bytes.Buffer) {
	buffer.WriteString(`
<h3>Welcome to `)
	hero.EscapeHTML(site, buffer)
	buffer.WriteString(`</h3>
<p>Open-source project available at <a href="https://github.com/OviCrisan/SiteGo">github.com/OviCrisan/SiteGo</a>. 
Or <a href="https://github.com/ovicrisan/SiteGo/releases">download released binaries</a> (Windows / Linux x64).</p>
<p>The goal is to create a very simple but fully functional customizable and configurable stateless 
<a href="https://golang.org/">Golang</a> website, which can be used to test multiple deployments, like Vagrant VMs,
Ansible Playbooks, Terraform scripts, Docker containers and Kubernetes clusters, with minimal overhead and no runtimes.</p>
<p>Read more <a href="about">about this project</a>.</p>
`)

}
