apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: sitego
  name: sitego
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sitego
  template:
    metadata:
      labels:
        run: sitego
    spec:
      containers:
      - image: ovicrisan/sitego
        imagePullPolicy: IfNotPresent  #Always
        name: sitego
        ports:
        - containerPort: 8000
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: sitego
  name: sitego
  namespace: default
spec:
  clusterIP: 10.100.0.54
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31475
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: sitego
  type: NodePort
status:
  loadBalancer: {}